# Generated by Django 4.1.3 on 2022-12-02 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('ctype', models.CharField(choices=[('Weekday', 'Weekday'), ('Weekend', 'Weekend')], max_length=10, null=True)),
                ('fee', models.IntegerField(null=True)),
                ('medium', models.CharField(choices=[('Sinhala', 'Sinhala'), ('English', 'English'), ('Tamil', 'Tamil')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('bdate', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('other_phone', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='St_Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quali_type', models.CharField(choices=[('A/L', 'A/L'), ('O/L', 'O/L'), ('HND', 'HND'), ('BSc', 'BSc'), ('MSc', 'MSc'), ('MBA', 'MBA'), ('PHD', 'PHD')], max_length=10, null=True)),
                ('quali_detail', models.CharField(max_length=100, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sims_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(auto_now_add=True, null=True)),
                ('pay_type', models.CharField(choices=[('Downpay', 'Downpay'), ('RegFee', 'RegFee'), ('Installements', 'Installements'), ('CertificateFee', 'CertificateFee'), ('Other', 'Other')], max_length=30, null=True)),
                ('pay_note', models.CharField(max_length=80, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sims_app.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sims_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=10, null=True, unique=True)),
                ('module', models.CharField(max_length=25, null=True)),
                ('marks', models.IntegerField(null=True)),
                ('grade', models.CharField(max_length=1, null=True)),
                ('comment', models.CharField(max_length=80, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sims_app.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sims_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sims_app.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sims_app.student')),
            ],
        ),
    ]
