# Generated by Django 4.1.3 on 2022-12-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
