# Generated by Django 4.1.3 on 2022-12-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims_app', '0005_alter_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to='images/'),
        ),
    ]
