# Generated by Django 4.1.3 on 2023-02-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sims_app', '0011_alter_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sims_app.course'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sims_app.student'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sims_app.course'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sims_app.student'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sims_app.course'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sims_app.student'),
        ),
        migrations.AlterField(
            model_name='st_qualification',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sims_app.student'),
        ),
    ]
